use std::fmt::Display;

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum TokenKind {
    OpenAngBrack,
    CloseAngBrack,
    OpenCurlBrack,
    CloseCurlBrack,
    CloseParenth,
    OpenParenth,
    Slash,
    Assign,
    Plus,
    Minus,
    Asterisk,
    AtSymbol,
    Identifier,
    For,
    In,
    If,
    Percent,
    Integer,
    Float,
    Period,
    Colon,
    Slot,
    EOF,
    #[default]
    Unknown,
    Pixels,
    Degrees,
    Radians,
    Comment,
    Comma,
    String,
    Hashtag,
    Range,
    Remainder,
    OpenSquareBrack,
    CloseSquareBrack,
    Eq,
    LessOrEq,
    MoreOrEq,
    Not,
    NotEq,
    VertLine,
    Or,
    Ampersand,
    And,
    Exp,
    PathSep,
    Bind,
}

impl Display for TokenKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            TokenKind::OpenAngBrack => "\"<\"",
            TokenKind::CloseAngBrack => "\">\"",
            TokenKind::OpenCurlBrack => "\"{\"",
            TokenKind::CloseCurlBrack => "\"}\"",
            TokenKind::CloseParenth => "\")\"",
            TokenKind::OpenParenth => "\"(\"",
            TokenKind::Slash => "\"/\"",
            TokenKind::Assign => "\"=\"",
            TokenKind::Plus => "\"+\"",
            TokenKind::Minus => "\"-\"",
            TokenKind::Asterisk => "\"*\"",
            TokenKind::AtSymbol => "\"@\"",
            TokenKind::Identifier => "identifier",
            TokenKind::For => "for",
            TokenKind::In => "in",
            TokenKind::If => "if",
            TokenKind::Percent => "\"%\"",
            TokenKind::Integer => "integer",
            TokenKind::Float => "float",
            TokenKind::Period => "\".\"",
            TokenKind::Colon => "\":\"",
            TokenKind::Slot => "slot",
            TokenKind::EOF => "end of line",
            TokenKind::Unknown => "<UNKNOWN>",
            TokenKind::Pixels => "px",
            TokenKind::Degrees => "deg",
            TokenKind::Radians => "rad",
            TokenKind::Comment => "comment",
            TokenKind::Comma => "\",\"",
            TokenKind::String => "string",
            TokenKind::Hashtag => "\"#\"",
            TokenKind::Range => "\"..\"",
            TokenKind::Remainder => "\"%%\" (remainder)",
            TokenKind::OpenSquareBrack => "\"[\"",
            TokenKind::CloseSquareBrack => "\"]\"",
            TokenKind::Eq => "\"==\"",
            TokenKind::LessOrEq => "\"<=\"",
            TokenKind::MoreOrEq => "\">=\"",
            TokenKind::Not => "\"!\"",
            TokenKind::NotEq => "\"!=\"",
            TokenKind::VertLine => "\"|\"",
            TokenKind::Or => "\"||\"",
            TokenKind::Ampersand => "\"&\"",
            TokenKind::And => "\"&&\"",
            TokenKind::Exp => "\"^\"",
            TokenKind::PathSep => "\"::\"",
            TokenKind::Bind => "binding",
        };
        write!(f, "{}", s)
    }
}
